### ISSUE TITLE
Add Criteria like Type Safe query API to externalize Cypher Query Language

### ISSUE THREAD

**Issue by hantsy** [neo4j/sdn-rx#106]
JPA, Spring Data MongoDB provides a [`Criteria`](https://docs.spring.io/spring-data/mongodb/docs/current/api/org/springframework/data/mongodb/core/query/Criteria.html) class to build the query in a fluent approach, but I can not find similar functionality in SDN RX. 

The  `ReactiveNeo4jOperations.findAll` accepts `Statement`, but how to build a `Statement` quickly using Spring Data Mongo's Criteria-like API. 

Hope SDN RX provides similar Criteria to externalize Cypher syntax.

**Comment by meistermeier** [comment]
I do not think that it is the level of abstraction you are looking for but we have a (waiting to get stable) Cypher API (Start the queries with methods of the [Cypher](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/cypher/Cypher.java) class) You can see some of its usage in this [test](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/core/cypher/CypherIT.java) but it is also used in the framework's code base to create the `Statements`.

**Comment by hantsy** [comment]
@meistermeier Thanks. That is what I need. But I think it is better to describe the usage in the SDN-rx docs.

**Comment by meistermeier** [comment]
The API is still in development and not yet considered to be stable. We are currently working on a more comprehensive documentation that will also include the Cypher API aspect.
