### ISSUE TITLE
@CreatedDate is not set  as expected when saving a node

### ISSUE THREAD

**Issue by hantsy** [neo4j/sdn-rx#109]
The complete code is [here](https://github.com/hantsy/spring-kotlin-coroutines-sample/tree/master/data-neo4j-rx-cypher).

To experience the auditing feature in Sdnrx, I [added `@EnableNeo4jAuditing` on the Application class.](https://github.com/hantsy/spring-kotlin-coroutines-sample/blob/master/data-neo4j-rx-cypher/src/main/kotlin/com/example/demo/DemoApplication.kt#L31) .

And declare a `Post` Node as Kotlin data class as following.

```kotlin
@Node
data class Post(
        @Id
        @GeneratedValue(value = UUIDStringGenerator::class)
        val id: String? = null,
        val title: String? = null,
        val content: String? = null,

        @CreatedDate
        val createdAt: LocalDate? = null,

        @LastModifiedDate
        val updatedAt: LocalDate? = null
)
```

And  insert some sample data by listening `ApplicationReadyEvent`.

```kotlin
@Component
class DataInitializer(private val postRepository: PostRepository) {

    @EventListener(value = [ApplicationReadyEvent::class])
    fun init() {
        println(" start data initialization  ...")

        runBlocking {
            postRepository.deleteAll()
            postRepository.init()
        }

        println(" done data initialization  ...")

    }

}
```

When I start up the application and verify the inserted data using `curl`:

```bash
curl http://localhost:8080/posts
[{"id":"893c19f9-dc21-4d75-83a2-58ace67acd55","title":"My first post title","content":"Content of my first post","createdAt":null,"updatedAt":"2020-01-09"},{"id":"72d9b08e-0ddf-499f-808f-10dba4d62a91","title":"My second post title","content":"Content of my second post","createdAt":null,"updatedAt":"2020-01-09"}]
```

The `createdAt` is not inserted as expected.

**Comment by meistermeier** [comment]
Thanks for reporting 🙇‍♀ I could reproduce it and it will get fixed with linked PR.
