### ISSUE TITLE
Maven central missing spring-data-neo4j-rx:1.0.0-beta02

### ISSUE THREAD

**Issue by haris-zynka** [neo4j/sdn-rx#122]
When using "org.neo4j.springframework.data:spring-data-neo4j-rx-spring-boot-starter:1.0.0-beta02" with Gradle I get message "Could not resolve org.neo4j.springframework.data:spring-data-neo4j-rx:1.0.0-beta02". Not sure why can't it link to RX but it appears that some dependency is broken.

**Comment by meistermeier** [comment]
Could you provide your `build.gradle` file? Because it is available in Maven central (https://repo1.maven.org/maven2/org/neo4j/springframework/data/spring-data-neo4j-rx-spring-boot-starter/1.0.0-beta02/) I assume it is a local problem on your side.

**Comment by haris-zynka** [comment]
I too did searched it on maven central and found it which is why I posted here. I did it on 2 computers one from work and one at home.

`import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.2.3.RELEASE"
	id("io.spring.dependency-management") version "1.0.8.RELEASE"
	kotlin("jvm") version "1.3.61"
	kotlin("plugin.spring") version "1.3.61"
}

group = "asdasdasdasdasdasd"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
	mavenCentral()
}

dependencies {
	implementation("org.neo4j.springframework.data:spring-data-neo4j-rx:1.0.0-beta02")
	implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("org.springframework.boot:spring-boot-starter-data-mongodb-reactive")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
	}
	testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}`
![image](https://user-images.githubusercontent.com/54882877/73054363-8837f900-3e8a-11ea-8fca-e5d6c4bd880f.png)

That's the one without the Spring Boot. Next is Spring Boot which details you can find here https://neo4j.com/developer/spring-data-neo4j-rx/#generate-gradle-project
I just replace dependency with `"org.neo4j.springframework.data:spring-data-neo4j-rx-spring-boot-starter:1.0.0-beta02"` and I still get the same issue. Now if boot one depends on the first one without the boot it's pretty clear to me that the neo4j-rx one has issues. I'm not sure how to fix this even if it's both of my local pcs.

![image](https://user-images.githubusercontent.com/54882877/73054611-275cf080-3e8b-11ea-9e96-7b8f9e838a55.png)

**Comment by haris-zynka** [comment]
Update on it. It appears after
```sh 
clean buildNeeded
``` 
it gives more details
![image](https://user-images.githubusercontent.com/54882877/73061733-1fa54800-3e9b-11ea-9087-e17726d0b946.png)

**Comment by meistermeier** [comment]
Thanks, exactly this is what I am seeing now.
Some background on this: We have defined a BOM in SDN-RX and use one of its definition for testing. It seems that gradle wants to eagerly fetch it although it is not needed.

**Comment by haris-zynka** [comment]
I'm not sure if you guys can solve this so I'm gonna try something myself. If you want you can close the issue as it appears it's not on your side but rather gradle dependency management.

**Comment by meistermeier** [comment]
We will upgrade the dependency to the release version. You could fix it by also adding
`maven { url = uri("https://repo.spring.io/snapshot") }`
to the dependency list.

**Comment by haris-zynka** [comment]
> We will upgrade the dependency to the release version. You could fix it by also adding
> `maven { url = uri("https://repo.spring.io/snapshot") }`
> to the dependency list.

Thx

**Comment by meistermeier** [comment]
If you are still having a "broken" project at hand, it would be good to know if the problem does not appear if you clean the gradle cache and then resolve the dependencies again.

**Comment by haris-zynka** [comment]
> If you are still having a "broken" project at hand, it would be good to know if the problem does not appear if you clean the gradle cache and then resolve the dependencies again.

Sorry, didn't see this before, but I started working with the provided solution before so I cant verify this.
