### ISSUE TITLE
Switching databases for each HTTP request.

### ISSUE THREAD

**Issue by haris-zynka** [neo4j/sdn-rx#126]
I failed to find how to switch the database. I'm creating a multi-tenant solution and need to switch databases frequently depending on a client. It would be good to be able to just shoot out the database name from somewhere but based on each HTTP request. Is this possible at all?
Thanks

**Comment by michael-simons** [comment]
Hi, I'm unsure what you mean by "for each HTTP request". The planned support for multi database has just landed with commit fd8068b24e5a80fc1ded6e5a884ddd6447de9c02 and you find an example here https://github.com/neo4j/sdn-rx/blob/master/examples/multi-database/src/test/java/org/neo4j/springframework/data/examples/spring_boot/ExampleUsingDynamicDatabaseNameTest.java. That example selects the database based on the Spring Security principal.

Please have a look for further questions on our community site: https://community.neo4j.com Thank you :)
