### ISSUE TITLE
Double bean initialisation with Spring Boot

### ISSUE THREAD

**Issue by haris-zynka** [neo4j/sdn-rx#133]
Hi, I'm having an issue with the `@EnableReactiveNeo4jRepositories`. If I add it above a configuration I get this
![image](https://user-images.githubusercontent.com/54882877/73836487-ab11c800-480f-11ea-8ebb-db6a422313a6.png)
It appears that Reactive + Imperative ones are getting started at the same time but I'm not sure in which order and exactly how. Debuging showed me that Imperative one will trigger first. Then for some reason it will create a reactive repository bean. Other attempt to create it will of course fail.

So:

1.  Set _`@EnableReactiveNeo4jRepositories(basePackages=["somepackages"])_ ` will crash app as it will try to double initialise same bean. If annotation _@EnableNeo4jRepositories_ is set to empty list for _basePackages_ it still initialises beans from reactive repository
2. If annotation removed it starts but **only** if Neo4j is the only source
3. If annotation is not present but another data source is, it will try to initialise other data sources repositories. In my case MongoDB bean gets triggered for creation also by _org.neo4j.springframework.boot.autoconfigure.data.Neo4jReactiveRepositoriesConfiguration_ class 

Not sure how to avoid this but I'm pretty sure that repositories that do not extend ReactiveNeo4jRepository should not be scanned by Neo4j repositories configuration

**Comment by michael-simons** [comment]
I wonder why you have 3 times in the log… I would have understand two times, but not 3.

Would you mind sharing

* your `pom.xml` or Gradle equivalent
* your `@Configration` classes
* your `application.properties` or `.yml`

In the meantime, I guess you want only mongo and neo4j reactive. I have no idea about mongo, but add 

```
spring.data.neo4j.repositories.type=reactive
```

to your config and please report back.

**Comment by haris-zynka** [comment]
Hi, this was the configuration `kotlin
@Configuration
@EnableNeo4jRepositories("ai.d****.repositories.graph")
@EnableAutoConfiguration
class Neo4jConfig {
    @Bean
    fun databaseNameResolver(): DatabaseSelectionProvider {
        val dbName = CurrentRealmResolver.getRealmHeader()
        return DatabaseSelectionProvider { DatabaseSelection.byName(dbName) }
    }
}`
And package ...repositories.graph was only for Neo4j which was really confusion as to why would it try to instantiate Mongo ones which were isolated in repositories.geo. However I remember removing `@EnableAutoConfiguration` but still having the same issue. Now it's completely different I have no config only DbNameResolver which is reactive one and works. Problem remains as I've removed `@EnableNeo4jRepositories` it still tries to instantiate everything related to repositories. It fires up twice which is OK since imperative ones have 0 detected repos. To solve this I actually moved mongo repositories out of the main package so it's now split in a way that com.test.mongo is isolated from main app com.test.api where Neo4j tries to fight for all repositories.

gradle was something like `
import org.jetbrains.kotlin.gradle.tasks.KotlinCompile

plugins {
	id("org.springframework.boot") version "2.2.3.RELEASE"
	id("io.spring.dependency-management") version "1.0.8.RELEASE"
	kotlin("jvm") version "1.3.61"
	kotlin("plugin.spring") version "1.3.61"
}

group = "ai.d***"
version = "0.0.1-SNAPSHOT"
java.sourceCompatibility = JavaVersion.VERSION_11

repositories {
	mavenCentral()
	maven { url = uri("https://repo.spring.io/snapshot") }
}

dependencies {
	implementation("org.springframework.boot:spring-boot-starter-actuator")
	implementation("org.neo4j.springframework.data:spring-data-neo4j-rx-spring-boot-starter:1.0.0-beta03")
	implementation("org.springframework.boot:spring-boot-starter-oauth2-client")
	implementation("org.springframework.boot:spring-boot-starter-webflux")
	implementation("org.springframework.boot:spring-boot-starter-data-mongodb-reactive")
	implementation("com.fasterxml.jackson.module:jackson-module-kotlin")
	implementation("org.jetbrains.kotlin:kotlin-reflect")
	implementation("org.jetbrains.kotlin:kotlin-stdlib-jdk8")
	implementation("org.jetbrains.kotlinx:kotlinx-coroutines-reactor")
	testImplementation("org.springframework.boot:spring-boot-starter-test") {
		exclude(group = "org.junit.vintage", module = "junit-vintage-engine")
	}
	testImplementation("io.projectreactor:reactor-test")
}

tasks.withType<Test> {
	useJUnitPlatform()
}

tasks.withType<KotlinCompile> {
	kotlinOptions {
		freeCompilerArgs = listOf("-Xjsr305=strict")
		jvmTarget = "1.8"
	}
}
`
The only difference is that I removed package names which expose client name (just in case).

However thank you for the configuration advice since I don't need non reactive ones, but when I debugged, as I said, I see that Reactive repositories are getting triggered twice. I have no idea why. 

Also ThreadLocal example is present as example for multi tenancy however it will not work for reactive style. `kotlin
@Component
class RealmFilter : WebFilter {
    override fun filter(exchange: ServerWebExchange, chain: WebFilterChain): Mono<Void> {
        val realmId = exchange.request.headers.getFirst(CurrentRealmResolver.tenantHeaderName) ?: "zdb"
        return chain.filter(exchange).subscriberContext { it.put(CurrentRealmResolver.tenantHeaderName, realmId) }
    }
}

@Component
class CurrentRealmResolver {

    fun getRealmFromContext(): Mono<String> = Mono.subscriberContext().map {
        it.getOrDefault(tenantHeaderName, "db") ?: "db"
    }

    companion object {
        const val tenantHeaderName = "X-REALM-ID"
    }
}

@Component("reactiveDatabaseSelectionProvider")
class ReactiveDbSelectionProvider : ReactiveDatabaseSelectionProvider {
    @Autowired
    lateinit var resolver: CurrentRealmResolver

    override fun getDatabaseSelection(): Mono<DatabaseSelection> {
        return resolver.getRealmFromContext().map { DatabaseSelection.byName(it) }
    }

}
`
I can put something like that as example project for multi tenancy with reactive Neo4j (and thank you for making this so easy I had really ugly problems with Mongo) because Reactor Context needs to be taken care of as ServerHttpRequest is not easily Autowired in WebFlux.

**Comment by michael-simons** [comment]
Regarding database selection: We have [`ReactiveDatabaseSelectionProvider`](https://github.com/neo4j/sdn-rx/blob/1.0.0-beta03/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/ReactiveDatabaseSelectionProvider.java)

If you put `org.springframework.boot:spring-boot-starter-data-mongodb-reactive` on the class path, it will trigger the auto configuration for Mongo. I think as expected? I have to read through your comments a couple of more times.

**Comment by haris-zynka** [comment]
> Regarding database selection: We have [`ReactiveDatabaseSelectionProvider`](https://github.com/neo4j/sdn-rx/blob/1.0.0-beta03/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/ReactiveDatabaseSelectionProvider.java)
> 
> If you put `org.springframework.boot:spring-boot-starter-data-mongodb-reactive` on the class path, it will trigger the auto configuration for Mongo. I think as expected? I have to read through your comments a couple of more times.

1. Mongo is configured and working properly. It scans only package provided through `@EnableReactiveMongoRepositories("basepackagename")`, doesn't bother with Neo4j ones because they extend ReactiveNeo4jRepository interface
2. Neo4j reactive is configured to scan only 1 package intended for it's own repositories
3. Neo4j reactive scan fires up second time and scans all repositories, regardless of the interface, even ones that extend ReactiveMongoRepositories.
4. Moving Mongo repositories out of the base pacakage where `@SpringBootApplication` is located fixes the problem

Hope this makes more sense now. I don't know how to explain it better / simple. Basically by debuging application I've noticed that factory for reactive Neo4j repositories beans is trying to require interface that extends ReactiveMongoRepository<,>. I even tried without annotation `@Repository` it's still doing the same thing.

**Comment by michael-simons** [comment]
Yep, that makes sense!

I'll be unavailable next week, but I'm gonna take care of it. 
Thanks for reporting.

**Comment by michael-simons** [comment]
I noticed that you are using `@EnableNeo4jRepositories`. That might as be the one from Spring Data Neo4j (SDN) and Spring Boot. SDN is *not* SDN-RX.

Make sure you use `org.neo4j.springframework.data.repository.config.EnableReactiveNeo4jRepositories` or `org.neo4j.springframework.data.repository.config.EnableNeo4jRepositories`, but I guess you want the first one.

**Comment by michael-simons** [comment]
`org.neo4j.springframework.data.repository.config.EnableNeo4jRepositories` would work… But you will get imperative repositories,

`org.neo4j.springframework.data.repository.config.EnableReactiveNeo4jRepositories` has a bug indeed. Will be fixed in the next milestone.

**Comment by haris-zynka** [comment]
Hi, I've switched to `org.neo4j.springframework.data.repository.config.EnableReactiveNeo4jRepositories`. Problem is still present. Just wanted to report.
And thank you.
Until bug is fixed anyone who has the same issue can move repositories away from main package where SDN/RX will try to request all repositories regardless of their type
