### ISSUE TITLE
Provide a way of defining custom queries in a static, type safe way.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#181]
The idea is to use the Cypher-DSL inside the `@Query` annotation. The simplest option would be providing suppliers of statements:

```
	@API(status = EXPERIMENTAL, since = "1.0")
	Class<? extends StatementSupplier> statementSupplier() default DefaultQuerySupplier.class;

	@API(status = EXPERIMENTAL, since = "1.0")
	interface StatementSupplier extends Supplier<Statement> {
	}


	class PersonByNameStatementSupplier implements Query.StatementSupplier {

		@Override
		public Statement get() {
			return Cypher.match(
				node("PersonWithAllConstructor").named("n").properties(mapOf("name", Cypher.parameter("name"))))
				.returning("n").build();
		}
	}

	@Query(statementSupplier = PersonByNameStatementSupplier.class)
	Optional<PersonWithAllConstructor> getOptionalPersonViaStatementSupplier(@Param("name") String name);
```

With classes all over the place (one for each statement). We discussed possible lookups with method handles. 

Also nice to have would be something along the test introduced in #180 so that standalone building blocks - mostly reassembly Cypher `with` blocks can be reused and stacked together.

This is a place holder for a pre 1.0 release.

**Comment by meistermeier** [comment]
https://jira.spring.io/browse/DATAGRAPH-1349
