### ISSUE TITLE
Getting "Unable to convert com.some.Some$SomeEnum to Neo4j Value."

### ISSUE THREAD

**Issue by bojanv55** [neo4j/sdn-rx#202]
Using:

```
                 <dependency>
			<groupId>org.neo4j.springframework.data</groupId>
			<artifactId>spring-data-neo4j-rx-spring-boot-starter</artifactId>
			<version>1.0.0</version>
		</dependency>
```

and SpringBoot with my repo that `extends ReactiveNeo4jRepository<Some, String> {` 

where

```
@Data
@Node
public class Some {
    @Id
    private SomeEnum naziv;

    @AllArgsConstructor
    @Getter
    public enum SomeEnum {
        MY("my"),
```

and getting that exception that it cannot convert Enumeration to value.

**Comment by meistermeier** [comment]
Thanks for reporting this. It seems that the implicit converter does not get called for identifier.
On the other hand it seems only for a hand full of nodes a good idea to use enums as identifiers.

**Comment by meistermeier** [comment]
Decision: Let's convert also the id types transparently.
