### ISSUE TITLE
Add documentation about relationship

### ISSUE THREAD

**Issue by meistermeier** [neo4j/sdn-rx#209]
Add a chapter about relationship details that include `@RelationshipProperties` and dynamic relationships.

Original:
Is there any documentation for this? Specifically regarding properties on relationships.

_Originally posted by @optama in https://github.com/neo4j/sdn-rx/pull/101#issuecomment-618921021_

**Comment by optama** [comment]
Until then - `@RelationshipProperties` is mentioned at https://medium.com/neo4j/spring-data-neo4j-rx-beta-iii-79573a773584. Beta III though so things might've changed since then.
