### ISSUE TITLE
Please add Feature request in issues as it is in neo4j repo

### ISSUE THREAD

**Issue by aaramg** [neo4j/sdn-rx#211]

**Comment by meistermeier** [comment]
?

**Comment by aaramg** [comment]
I mean in GitHub repo would be nice to have 2 options: Bugs and Feature Request :)
Also for your convenience. It will be easy to see the issue is bug or nice to have :)

**Comment by meistermeier** [comment]
Now I understand. Yes, we already considered creating templates for the issues (bug / feature request).
