### ISSUE TITLE
FeatureRequest: Would be great to have global filter on class level annotation

### ISSUE THREAD

**Issue by aaramg** [neo4j/sdn-rx#212]
It would be great to have an annotation on class to filter queries automatically with any requests.
For example, during the soft deletion developers used to set deleted date or some other deleted flags to mark the entity as deleted. So in your case, it will be the Node.

`@Where(clause = "deleted is null")`
The following code snippet shows a @Where annotation that excludes a record if its state is DELETED. This is used in Hibernate tech stack.
So what it does? When someone calls findById(id) and the node is found but the "deleted" date is set there it counts it as deleted because of @Where and does not return the Node. 
This helps when in your whole project everything is soft deletable you should write in any query the part which excludes the Nodes which have deleted property with date already set.
findById -----> findByIdAndDeletedIsNull . And any other queries should have this suffix "**andDeletedIsNull"
The annotation could be @Filter and in that case, it would work as permitter.
it could be smth like this: `@Filter(where = "deleted is null")` and we could put it on class level.

The example concerns soft deletion but I guess it could serve globally for everything.

**Comment by michael-simons** [comment]
Thanks for the interesting aspect, which I have used in previous projects as well.

Just brainstorming a bit:

* How dynamic does it have to be? I think the annotation should support SpEL (Spring Expression Language) as well
* I think it would be useful having it on finder methods on repositories as well
* Does it need controls in which scenario it should be applied (read, delete, update)? Propably.

What do you think, @aaramg ?

**Comment by aaramg** [comment]
Ok, let's brainstorm :)
1. The support of SpEL would be great to have I guess.
2. It would be an advantage to be able to set on repo methods, but I guess in that case naming and custom repo method definition would be enough. (f.ex. findByField1AndField2IsNull() because it is specific to that method and it is ok to write everything)
3. I guess being able to set it on the node entity class would be the best way. This feature I guess should be more globally thingy. Because in specific scenarios it should be specified in that specific part.

There is one conflict part.
Let's take there is a scenario that we have set on node entity class that anything is called on fetching your object, please filter deleted marked nodes on db level (smth. like `@Filter(where = "deleted is null")` //adding "deleted is null" at the end of where clause behind the scenes maybe) and don't return them, pretending that they never exist.
But maybe somehow admin user wants to get also the deleted ones. That is the dirty part I guess :) In Hibernate world there is a session-level flag to disable the global filters dynamically. But I guess it is not the nicest way to disable them. I guess there should be a marker annotation disabling the global filters on repo class or method level. That will solve the conflict. You will be able to write repo method or class that is used by admin and will be able to mark it with @DisableGlobalFilters annotation.

That is how I think about this feature request. :) Please write if I miss smth. :)

**Comment by michael-simons** [comment]
Given SpEL enabled, something like this on `@Node`

```
@Filter(where = "deleted is null", enabled = "#{someMagicSpEL}")
```

How about that?

**Comment by aaramg** [comment]
Interesting idea. 
Then we will be able to programmatically enable or disable the filter for specific resources.
I guess that is it. I have no idea right now what other properties of the annotation there can be a need. :)

P.S. Also on mention I can add:
This filter annotation would be nice to be able to set on the abstract parent class which is **not annotated** as `@Node` but **is inherited by** `@Node` classes. This will save a lot of time if you have a lot of `@Node` classes and they all need to have this filter.

P.S. I have another idea about the `@OrderBy` clause but will right it in a separate feature request of your repo. :)

**Comment by meistermeier** [comment]
Since we are in a migration process to the original Spring Data Neo4j and have to archive this repository, the issue also go migrated to: https://jira.spring.io/browse/DATAGRAPH-1348
Please watch or comment on the issue in Jira for further communication.
