### ISSUE TITLE
runtime managed labels

### ISSUE THREAD

**Issue by sergeily** [neo4j/sdn-rx#214]
it would be great to have runtime-managed-labels option such as OGM annotation @Labels

[ogm-manual](https://neo4j.com/docs/ogm-manual/current/reference/#reference:annotating-entities:node-entity:runtime-managed-labels)

**Comment by meistermeier** [comment]
Could you give an example for an use-case?
We did not bring this feature into the 1.0 because we consider labels as type descriptions/definitions. So it would make more sense for example to create new (derived/extending) classes/types in your domain to use if an entity change.

**Comment by sergeily** [comment]
Hi,

For example:
On our physical graph we have several logical subgraphs and part on nodes belongs to different subgraphs
Each subgraph (and accordingly each node) has own label.

Something like:
```
create (n:Column:GraphA:GraphB {name:'NodeA'})
create (n:Column:GraphA {name:'NodeB'})
create (n:Column:GraphA:GraphC {name:'NodeC'})
```


if we need to find path from NodeX to NodeY we use subgraph label (relevant path for specific subgraph)
also
When we need to find relationships of NodeX we use subgraph label

Node's subgraph is not permanent label and changed according to runtime conditions.
We can add node to subgraph (create if node not exists and add subgraph label) and connect to other nodes and also we can remove node from specific subgraph.
Add/Remove node to/from subgraph means add/remove subgraph label.

When we use [SDN+OGM it's possible to configure entity like](https://neo4j.com/docs/ogm-manual/current/reference/#reference:annotating-entities:node-entity:runtime-managed-labels)

```
@NodeEntity(label="Column")
public class DaeColumnNode extends DaeNode {
    ......
    private String name;
    ......
    @Labels
    private Set<String> labels;
    ......
}
```

and add/remove graph label at runtime.
