### ISSUE TITLE
Would be nice to have lazy loading in Relationships

### ISSUE THREAD

**Issue by aaramg** [neo4j/sdn-rx#215]
Smth like this I guess: @Relationship(lazy = true)

**Comment by meistermeier** [comment]
This is nothing we plan to support. SDN/RX should not act like JPA/Hibernate and execute queries without a call to an explicit persistent operation.
This would be the consequence when it comes to lazy loading.

**Comment by aaramg** [comment]
OK, I guess I understand what you mean. The depth of relationship should solve the problem. But what will happen if I call 
`Neo4jRepository findById("someUUID") or smth findByEmail("someemail@email.com");`
This should return the object will all its relationships in the whole depth???
What if the user relationships are so deep that it is smth like on Facebook. So let's take after login front end wants user details.
Please explain to me if I miss smth. I am really new in SDN.
Thanks a lot.

**Comment by aaramg** [comment]
By the way, in Spring Data Mongo also have lazy loading in @DBRef.
So this is smth I guess which is artificially added but it can help a lot.
`@DBRef(lazy = true)`
