### ISSUE TITLE
dynamic relationships

### ISSUE THREAD

**Issue by sergeily** [neo4j/sdn-rx#216]
it would be great to represent [dynamic relationships ](https://github.com/neo4j/sdn-rx/blob/master/docs/object-mapping/mapping.adoc#connecting-nodes-relationship) not as
`Map<String, AnnotatedDomainClass>`
but
`Map<String, Iterable<AnnotatedDomainClass>>`

**Comment by optama** [comment]
Yes I would also like to see something like this. Using dynamic relationship as it's currently implemented seems to only allow for max one relationship of each dynamic type.

**Comment by michael-simons** [comment]
Thanks for reporting it. Makes perfect sense.
