### ISSUE TITLE
Dynamic labels for @Node

### ISSUE THREAD

**Issue by singh-gurprit** [neo4j/sdn-rx#239]
Hello Neo4j, Thank you for the great work on reactive drivers.

It would be great if we can support Spring SpEL for @Node labels.

Use Case: Multi-Tenant application 

We could have a Supplier which computes the node label at run time:
`        @Bean("client")
	Supplier<String> client() {
		return ClientResolver::resolve;
	}`

And use the supplier inside Node annotation. 
`
@Node("#{ client.get() }_mynode")`

Thank you!

**Comment by meistermeier** [comment]
Since we are in a migration process to the original Spring Data Neo4j and have to archive this repository, the issue also go migrated to: https://jira.spring.io/browse/DATAGRAPH-1346
Please watch or comment on the issue in Jira for further communication.
