### ISSUE TITLE
[Cypher-DSL] cant use alias for property projection

### ISSUE THREAD

**Issue by Andy2003** [neo4j/sdn-rx#245]
**Description**

Given

```java
Statement statement;
Node n = Cypher.node("Person").named("p");

statement = Cypher.match(n)
	.returning(
		n.project("alias", n.property("name"))
	)
	.build();
```

Current behavior:

    MATCH (p:`Person`) RETURN p{alias: .name}

Expected behavior:
    
    MATCH (p:`Person`) RETURN p{alias: p.name}

**Comment by michael-simons** [comment]
Thanks Andreas, nice catch!
