### ISSUE TITLE
@Indexed annotation support

### ISSUE THREAD

**Issue by arramanenka** [neo4j/sdn-rx#249]
It would be really great to see support of Indexed annotation for model, alike non-reactive neo4j or just spring data mongodb.

As stated in [docs ](https://neo4j.com/docs/cypher-manual/current/administration/indexes-for-search-performance/)indexing of fields increases search speed of documents. Adding support to Indexed annotation as in org.springframework.data.mongodb.core.index.Indexed on fields of Node model, would allow developers to add index for documents in a fast and easy manner.

**Comment by meistermeier** [comment]
Index creation in SDN/OGM should be seen a support functionality during development. Sadly it was not seen as such by most developers.
This should be done directly on the server side and not via an application.

Side note: I think you meant the current Spring Data Neo4j when talking about non-reactive Neo4j. SDN-RX is not only reactive but has also imperative support.
