### ISSUE TITLE
Allow findBy on map relationships

### ISSUE THREAD

**Issue by benkuly** [neo4j/sdn-rx#262]
I want to query relationship nodes when they are defined as map.

Given `NodeA - RelationsshipProperties -> NodeB`:
```
@Node("NodeA") 
public class NodeA {
        @Id  
        private final String title;

        @Relationship(type = "RELATED_TO", direction = OUTGOING) 
        private Map<NodeB, RelationshipProperties> related = new HashMap<>();
// ...
}

@Node("NodeB") 
public class NodeB {
        @Id  
        private final String title;

        @Relationship(type = "RELATED_TO", direction = INCOMING) 
        private Map<NodeA, RelationshipProperties> related = new HashMap<>();
// ...
}
```
A Repository Interface-Method `Flux<NodeA> findByRelatedTitle(String title);` does currently try to access not present `title` on `RelationsshipProperties` instead of `NodeB`s title.

**Comment by michael-simons** [comment]
We're discussing atm how we could enhance our `@RelationshipProperties`-model to make this possible.

**Comment by meistermeier** [comment]
Since we are in a migration process to the original Spring Data Neo4j and have to archive this repository, the issue also go migrated to: https://jira.spring.io/browse/DATAGRAPH-1343
Please watch or comment on the issue in Jira for further communication.
