### ISSUE TITLE
Object mapping relationships do not work with polymorphic types

### ISSUE THREAD

**Issue by Solom00n** [neo4j/sdn-rx#269]
Hi everyone ! I'm using the version 1.1.1 of Spring Data Neo4j RX and I have a problem while defining a relationship property within a class hierarchy. In my use case, I have an abstract base class and several concrete implementations which extend it. Moreover, the base class has a property annotated with `@Relationship`, let's say with type REF: this kind of relationship is defined in the base class cause every concrete implementation actually has a type REF relationship, thus the relationship is a common property. 

> The @Node annotation is not inherited from super-types and interfaces. You can, however, annotate your domain classes individually at every inheritance level. This allows polymorphic queries: You can pass in a base or intermediate classes and retrieve the correct, concrete instance for your nodes. This is only supported for abstract bases annotated with @Node. The labels defined on such a class will be used as additional labels together with the labels of the concrete implementations.

Based on the above excerpt from the documentation and given the following object mapping:
```
@Node("A") public abstract class A {
    @Id @GeneratedValue public Long id;
    public String name ;
    
    @Relationship(type="REF) public X reference ;
    
    @Node("B") public static class B extends A {           // a concrete implementation B
        // ... specific B properties here
    }
    // ... other concrete implementations here
}

@Node("X") public abstract class X {                       // end node of the relationship REF
    @Id @GeneratedValue public Long id;

     // ... other specific X properties here
}
```
Using a repository class defined for node type A, what I expect here is that a call to findAll (or findById) returns the concrete implementation of A with the _reference_ property actually populated with an instance of the X object. Instead, what I get is a _null_ value for the _reference_ property. Furthermore, reading the log, I was able to verify that the generated query is correct and that it actually retrieves the related X object: executing the same query within the neo4j browser also work as expected. 

Is there a bug while mapping the query response to the actual object mapping, or have I missed something and my object mapping is not well defined?

**Note:** the above code is simplified for brevity but my real implementation makes use of Lombok, thus every property is actually private and accessed using the Lombok defined getter and setter.

**Comment by haris-zynka** [comment]
Hi, I also faced similar issues but in Kotlin and assumed problem was rather related to me using it instead of Java. Now my problem is that relationships never get populated if I use projections. If I use concrete class it will still be projection unless that class is annotated with some label. On the other hand I assume that because you use abstract class it tries to map it as projection instead of actual implementation. This is just assumption based on my experience from different tech stack and some of it is written here #271

**Comment by meistermeier** [comment]
Sorry for the late notice of the issue. We will investigate why this is (not) happening in the mapping phase.

**Comment by meistermeier** [comment]
Thanks for reporting this.
Since we are in a migration process to the original Spring Data Neo4j and have to archive this repository, the issue also go migrated to: https://jira.spring.io/browse/DATAGRAPH-1341
Please watch or comment on the issue in Jira for further communication.
