### ISSUE TITLE
Add java-module descriptors.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#27]
We should see how we can support the Java Plattform Module System (JPMS) while still being able to be used on JDK 8.

See among others https://blog.codefx.org/java/the-jpms-maturity-model/

**Comment by michael-simons** [comment]
I have looked into a couple of posts regarding multi-release jars (especially the one from @gunnarmorling [here](https://in.relation.to/2017/02/13/building-multi-release-jars-with-maven/)) and a couple of the Multi-Module or Projects [here](https://maven.apache.org/plugins/maven-compiler-plugin/multirelease.html), but the effort required for any of them is to high in my book for just having a module descriptor.

As much as I would love to work with JDK 11 and beyond in the main code base, the maintenance overhead for this is too high for just gaining a couple of things (which we need to maintain double as well).

So I'm gonna add defined automatic module names as we do already for https://github.com/neo4j/neo4j-java-driver-spring-boot-starter and OGM.

**Comment by gunnarmorling** [comment]
Thanks for tagging me :)

One option to consider is to add the module descriptor "out of bands" via
ModiTect:

    https://github.com/moditect/moditect

It also supports putting descriptors into the right place needed for an MR
Jar. This will make it a bit easier to add the descriptor, even allowing to
keep the build on JDK 8, if needed. But it requires proper (integration)
testing of the module produced that way.

**Comment by michael-simons** [comment]
Thanks a lot Gunnar :) I learned something new. I keep this in mind, but stick with the decision for the time being. We'll see how our VMWare Tanzu friends move forward with Spring Data Commons.
