### ISSUE TITLE
Can I use this package with neo4j 3.x.x

### ISSUE THREAD

**Issue by arabbani** [neo4j/sdn-rx#45]
Any word when this library will come into production release?

Can I use it with neo4j 3 or is it better now to use the older neo4j data with neo4j ogm for production

**Comment by michael-simons** [comment]
Hi,

We aim for a release by the end of this year.

The Bolt driver used by SDN/RX works with both Neo4j 3.5 and upcoming 4.0.
Only the reactive repositories depend on Neo4j 4.0 (as it is reactive up to the database itself), standard imperative repositories and the imperative client is usable with Neo4j 3.5.

We already have better Spring Data support in place than with SDN+OGM.

One feature missing is "rich relationships", that is: Properties on relationships.

Apart from that, we would recommend trying it out now.

**Comment by arabbani** [comment]
Great. Waiting for rich relationship
