### ISSUE TITLE
Add UUID converter.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#46]
It would be nice if a user could use `java.util.UUID` directly, without specifying a custom converter. The place to add this would be `org.neo4j.springframework.data.core.convert.AdditionalTypes`.

**Comment by mukundans91** [comment]
@michael-simons I can take a look at this if its still open. The idea is to convert UUID to String and vice versa right?

**Comment by michael-simons** [comment]
Hi @mukundans91 Yes, exactly. 

The infrastructure is in the [`convert`](https://github.com/neo4j/sdn-rx/tree/master/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/convert) package: 

`UUID` will be an [additional type]( https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/convert/AdditionalTypes.java).

One has to provide a pair of functions to read the `String` value from the `org.neo4j.driver.Value` into an `UUID` and write the  `UUID` back.

The conversion only has to check for `null` when writing to a `Value`.

We have integration tests in place, points of work would be the [map of expected values](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/shared/Neo4jConversionsITBase.java#L65-L91) and the node having attributes with all values [here](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/shared/Neo4jConversionsITBase.java#L170-L193) and the abomination that is [ThingWithAllAdditionalTypes](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/test/java/org/neo4j/springframework/data/integration/shared/ThingWithAllAdditionalTypes.java) ;)

You need Docker locally installed to run the tests. We use [Testcontainers](https://www.testcontainers.org).

Looking forward to your contribution.

**Comment by etSingh** [comment]
Hi @michael-simons, @mukundans91, 

Sorry I was a bit eager and you had provided a nice way to go about solving this issue so I went ahead and create a [PR](https://github.com/neo4j/sdn-rx/pull/65) 😅  

The only additional thing that I had to do apart from what you described above is to also include UUIDs in `org.neo4j.springframework.data.core.convert.Neo4jSimpleTypes`.

**Comment by michael-simons** [comment]
Thanks, @etSingh 

this shouldn't be a race of PRs and I'm unsure how to proceed right now. 

The basic change is correct, and yes, `UUID` needs to be added as a known simple type. Otherwise the Spring Data Commons infrastructure treats it as an association.

The added tests works, but there's one test know that is failing: `org.neo4j.springframework.data.integration.imperative.TypeConversionIT`. 

Not a major thing, though.

And sorry, we are still working on infrastructure that builds PRs and notifies GH.

**Comment by etSingh** [comment]
Hi @michael-simons,

I totally agree with what you're saying, I will be mindful not to work on something that someone else might have volunteered to work on already. Just only started contributing to open source projects so got a bit carried away this time.

No worries! Any way I could run the `IT` tests locally?

**Comment by michael-simons** [comment]
Hi @etSingh Thank you!
We have added some documentation for exactly that: https://github.com/neo4j/sdn-rx/blob/master/docs/build.adoc
