### ISSUE TITLE
Add support for rich relationships.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#47]
Properties on relationships are not yet mappable.

Suggested solution:

* Allow `org.neo4j.springframework.data.core.schema.Relationship` also on `Element.TYPE`
* Fail bootstrap when a class annotated with `@Relationship` is the element of a repository
* Also don't allow querying them with the yet to be defined template later
* The class annotated with `@Node` is the owner of the relationship.
* The class annotated that should be treated as the rich relationship _must_ be annotated with `@Relationship`
* The owning end of the relationship can be annotated with `Relationship`
* If one of possible two annotations has a non default `type` attribute, that shall be the type of the relationship
* If both have a non default `type` attribute, bootstrapping shall fail
* The inverse side of the relationship of the attribute in owning end _must_ be specified with `inverse` attribute in `@Relationship` on the owning attribute
* The type annotated with `@Relationship` will not contain both ends of the relationship
* No attribute inside the type annotated with `@Relationship` must be annotated with `@Relationship`, bootstrap shall fail in such cases.

**Comment by arabbani** [comment]
Very important feature. Waiting for this. Please keep us updated
