### ISSUE TITLE
Return List instead of Iterable from Neo4jRepository.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#51]
In all cases where currently an `Iterable` is returned on the `CrudRepository` interface, we should consider narrowing the type on the `Neo4jRepository` interface and implementation, so that users extending that interface can benefit from easier interaction.

**Comment by jansur** [comment]
Hi @michael-simons , I would like to take this issue if it is still open.

**Comment by michael-simons** [comment]
Hello @jansur Please go on! 👍

**Comment by jansur** [comment]
@michael-simons , should I narrow the type only for CrudRepository?  
As far Neo4jRepository extends PagingAndSortingRepository and QueryByExampleExecutor, these two also contain methods which return Iterable.

e.g. Iterable<T> findAll(Sort sort)

**Comment by michael-simons** [comment]
That's a good catch.

To have a consistent approach, everything method returning an `Iterable<T>` should return a `List`, that is

From `PagingAndSortingRepository`
* `#findAll(org.springframework.data.domain.Sort)`

From `CrudRepository`
* `#saveAll`
* `#findAll()`
* `#findAllById`

From `QueryByExampleExecutor`
* `#findAll(org.springframework.data.domain.Example<S>)`
* `#findAll(org.springframework.data.domain.Example<S>, org.springframework.data.domain.Sort)`

That has to happen on the interface `org.neo4j.springframework.data.repository.Neo4jRepository`, as for example Spring Data Mongo does it.

Thanks again, @jansur much appreciated already!

**Comment by siavashsoleymani** [comment]
Hello @jansur you are still work on this issue?

**Comment by jansur** [comment]
yes I do

**Comment by michael-simons** [comment]
Closed with 8bf4a41d0ce6e9d4e4e595bc8e697cf0bec4a959.
