### ISSUE TITLE
Add a Spring HATEOAS / Spring Data REST example.

### ISSUE THREAD

**Issue by michael-simons** [neo4j/sdn-rx#80]
We would like to provide an example of a "pure" Spring HATEOAS / Spring Data REST example, based on the same domain as the current imperative and reactive examples.

**Comment by viveksb007** [comment]
Hi @michael-simons,

I would like to work on it. Could you explain a bit more on what's needed.
From what I understand, you want similar [Person repository](https://github.com/neo4j/sdn-rx#getting-started) example using Spring HATEOAS. Could you clarify?

Thanks

**Comment by michael-simons** [comment]
Hi,

yes, something like that. I would recommend having a look at the imperative web example:

https://github.com/neo4j/sdn-rx/tree/master/examples/imperative-web

I would start there. You can copy the whole example into a new module.
The controllers should be removed, instead https://spring.io/projects/spring-data-rest#overview shall be applied to expose the movie and person repositories as rest resources.

This gives you an idea but for JPA: https://spring.io/guides/gs/accessing-data-rest/

**Comment by gmontalvo404** [comment]
Can i work in this?

**Comment by viveksb007** [comment]
@gmontalvo404 sure, please go ahead.

**Comment by meistermeier** [comment]
Hello @gmontalvo404 and @viveksb007 . Is there still interest on your side to provide the example?

**Comment by viveksb007** [comment]
@meistermeier won't be able to pursue this at the moment.

**Comment by meistermeier** [comment]
Closed with #134
