### ISSUE TITLE
@Configuration final error

### ISSUE THREAD

**Issue by monstrfolk** [neo4j/sdn-rx#90]
Getting an error when building with Spring for configurations being final.

        <dependency>
            <groupId>org.neo4j.springframework.data</groupId>
            <artifactId>spring-data-neo4j-rx-spring-boot-starter
            </artifactId>
            <version>1.0.0-beta01</version>
        </dependency> 

Caused by: org.springframework.beans.factory.parsing.BeanDefinitionParsingException: Configuration problem: @Configuration class 'Neo4jDataAutoConfiguration' may not be final. Remove the final modifier to continue.

Offending resource: class path resource [org/springframework/boot/autoconfigure/data/neo4j_rx/Neo4jDataAutoConfiguration.class]

**Comment by michael-simons** [comment]
Hi @monstrfolk 
SDN/RX is based on Spring Boot 2.2, which allows configuration classes to be final. 

Spring Boot 2.2 has been released a couple of weeks ago, if you upgrade your application, things will be good.

**Comment by michael-simons** [comment]
Thanks a lot for giving us a try!!
