### ISSUE TITLE
ArtifactId `spring-data-neo4j-rx-spring-boot-test-autoconfigure` is missing in the Maven central repository

### ISSUE THREAD

**Issue by hantsy** [neo4j/sdn-rx#92]
I tried to follow the example: https://github.com/neo4j/sdn-rx/tree/master/examples/reactive-web to update my sample and add some test codes.

But I found the artifactId `spring-data-neo4j-rx-spring-boot-test-autoconfigure` is missing in the Maven central repository. 

https://mvnrepository.com/artifact/org.neo4j.springframework.data

**Comment by michael-simons** [comment]
Yep, it has not been released. 

This module will give us some headache… We have now support for both a running database (the best solution is Testcontainers for that) and Neo4j test harness. The later however has changed drastically from 3.5 to 4.0. Will need some work here.

**Comment by michael-simons** [comment]
You can get binaries now from the actions tab, the `build` step will contain the latest artifacts.

**Comment by hantsy** [comment]
Great, test container is ok for Neo4j tests, but I hope there is an embedded Neo4j server provided with `@DataNeo4jTest` for test purpose, as the H2 provided for Data JPA. Thanks for your hard work, hope it will be available with Neo4j 4.0.0 final release.
