### ISSUE TITLE
Java enum not supported

### ISSUE THREAD

**Issue by monstrfolk** [neo4j/sdn-rx#93]
Get an error with enums when attempting to use RX with Spring 2.2 and Neo4j 4 beta release.

org.neo4j.driver.exceptions.ClientException: Unable to convert <enum type> to Neo4j Value.

Is there no enum support? What is a good workaround?

**Comment by michael-simons** [comment]
Thanks for reporting it, this is indeed a missing feature. 

Providing a custom [Neo4jConversions](https://github.com/neo4j/sdn-rx/blob/master/spring-data-neo4j-rx/src/main/java/org/neo4j/springframework/data/core/convert/Neo4jConversions.java) bean in your context with additional converters added through `public Neo4jConversions(Collection<?> converters)` should work.

Feature will be there soon.
