### ISSUE TITLE
Add RelationshipEntity Support

### ISSUE THREAD

**Issue by nearsyh** [neo4j/sdn-rx#99]
Currently, I can't find a way to add properties in a relationship. SDN has a RelationshipEntity annotation to support this use case. Can we have it in SDN-RX also?

**Comment by meistermeier** [comment]
Thanks for your interest in SDN/RX. We have an issue open regarding properties on relations (#47).
It is mainly focused on bringing the property support to relations but not on supporting the well-known `RelationshipEntity` construct, that would also bring relationship-centric data access.
If you think this is needed, we can discuss this here. If you are fine with "just" properties on relationships you can close this issue.

**Comment by nearsyh** [comment]
Thanks for you reply! I think properties on relationships are good enough.
